### ISSUE TITLE
Applet doesn't load and shows message "Applet not high enough"

### ISSUE THREAD

**Issue by afbarbaro** [leaningtech/cheerpj-appletrunner#53] opened 2021-12-03 14:45 UTC
To reproduce, simply to https://www.allstarpuzzles.com/division/01337.html and click on the browser extension to load the applet.

**Comment by carlopi** [comment] 2021-12-03 15:18
Thanks for reporting this, I can reproduce the issue.
A colleague will look into this and come back to you.

**Comment by alexp-sssup** [comment] 2021-12-05 17:02
The problem is fixed in version 10.5 of CheerpJ Applet Runner. Make sure the extension is updated before trying again.

We would really appreciate if you could remove or upgrade your negative review. Thank you.

**Closed by alexp-sssup** 2021-12-05 17:02 UTC

**Comment by afbarbaro** [comment] 2021-12-05 17:36
Thank you so much! I've updated my rating - 5 stars
